### ISSUE TITLE
Add Node 18 support

### ISSUE THREAD

**Issue by Smokey-Joe123** [asednev/homebridge-plugin-govee-thermometer-hygrometer#78]
Please add support for Node 18. Currently this plugin fails to start with Node 18 installed, and various other Homebridge plugins I use now require v18 to update. Thanks!

**Comment by SemoTech** [comment]
@asednev Hey Alexey, any updates on progress towards support of Node.JS 18.x ?  The plugin keeps failing...

```
[11/27/2022, 10:29:01 AM] ====================
[11/27/2022, 10:29:01 AM] ERROR LOADING PLUGIN homebridge-plugin-govee:
[11/27/2022, 10:29:01 AM] Error: The module '/homebridge/node_modules/homebridge-plugin-govee/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 108. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1243:18)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-plugin-govee/node_modules/@abandonware/bluetooth-hci-socket/lib/native.js:6:15)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-plugin-govee/node_modules/@abandonware/bluetooth-hci-socket/index.js:8:20)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
[11/27/2022, 10:29:01 AM] ====================
```

**Comment by SemoTech** [comment]
FYI to all:

**Looks like all the functionality of this plugin has been fully integrated into [THIS](https://github.com/bwp91/homebridge-govee) one, plus other features, as the developers collaborated on a consolidation.**

**Comment by asednev** [comment]
@SemoTech sorry no updates at this time.

**Comment by smokeyjoe1234** [comment]
> FYI to all:
> 
> **Looks like all the functionality of this plugin has been fully integrated into [THIS](https://github.com/bwp91/homebridge-govee) one, plus other features, as the developers collaborated on a consolidation.**

Unfortunately that didn't work with my H5075 and returned NaN for the values. I was hoping to avoid digging into it when this one 'just works'.


> @SemoTech sorry no updates at this time.

Thanks for the reply - are there any plans to update in the near future or should I switch to the other plugin as Semotech suggested?

**Comment by Smokey-Joe123** [comment]
> FYI to all:
> 
> **Looks like all the functionality of this plugin has been fully integrated into [THIS](https://github.com/bwp91/homebridge-govee) one, plus other features, as the developers collaborated on a consolidation.**

Unfortunately that didn't work with my H5075 and returned NaN for the values. I was hoping to avoid digging into it when this one 'just works'.

> @SemoTech sorry no updates at this time.

Thanks for the reply - are there any plans to update in the near future or should I switch to the other plugin as Semotech suggested?

**Comment by asednev** [comment]
Maintaining this plugin is not my top priority at the moment. I will look at what it takes to support Node 18 time permitting. I also welcome contributions from the community. The limiting factor might be a dependency on @abandonware/bluetooth-hci-socket which hasn't been updated in over a year.

**Comment by nimda2** [comment]
> Please add support for Node 18. Currently this plugin fails to start with Node 18 installed, and various other Homebridge plugins I use now require v18 to update. Thanks!

Work with Version 20
