### ISSUE TITLE
Could not start scanning, state is unauthorized (not poweredOn)

### ISSUE THREAD

**Issue by Borsti-Alz** [asednev/homebridge-plugin-govee-thermometer-hygrometer#80]
Hello,
I am new in the hole Homebridge topic.
I have bought some Govee H5075 and installed the plugin as described in the installing instructions.
My operating system is macOs Monterey in Version 12.6.2.

When I start the plugin, the console give me the following message out:

Error: Could not start scanning, state is unauthorized (not poweredOn)
    at Noble.scan (/usr/local/lib/node_modules/homebridge-plugin-govee/node_modules/govee-bt-client/node_modules/@abandonware/noble/lib/noble.js:107:21)
    at Object.onceWrapper (node:events:628:26)
    at Noble.emit (node:events:513:28)
    at Noble.onStateChange (/usr/local/lib/node_modules/homebridge-plugin-govee/node_modules/govee-bt-client/node_modules/@abandonware/noble/lib/noble.js:87:8)
    at NobleMac.emit (node:events:513:28)

I hope you can help me!
Thanks in advance!

**Comment by asednev** [comment]
This is due to security in macOS.

https://github.com/asednev/homebridge-plugin-govee/issues/74 has steps to resolve your issue.
